# Generated by Django 5.0.6 on 2024-06-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0014_alter_formulir_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pendaftar',
        ),
    ]
