# Generated by Django 5.0.6 on 2024-06-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0017_alter_formulir_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulir',
            name='account',
        ),
    ]
